/** @format */

import {Platform, StyleSheet} from 'react-native';
// import {FontFamily} from '../constants';
import {moderateScale} from './scales';
import {lightTheme} from './themes';
// import {FontFamily} from '../constants/font-family';

const themeStyles = StyleSheet.create({
  // Flex Sizes
  flex1: {flex: 1},
  flex2: {flex: 2},
  flex3: {flex: 3},
  flex4: {flex: 4},
  f1: {flex: 0.1},
  f2: {flex: 0.2},
  f3: {flex: 0.3},
  f4: {flex: 0.4},
  f5: {flex: 0.5},
  f6: {flex: 0.6},
  f7: {flex: 0.8},
  // Width
  fullWidth: {width: '100%'},
  halfWidth: {width: '50%'},
  widthAuto: {width: 'auto'},
  width40: {width: '40%'},
  width60: {width: '60%'},
  width80: {width: '80%'},
  // Height
  heightAuto: {height: 'auto'},
  fullHeight: {height: '100%'},
  // Spacing - Padding
  p0: {padding: 0},
  p5: {padding: 5},
  p10: {padding: 10},
  p15: {padding: 15},
  p20: {padding: 20},
  p25: {padding: 25},
  p30: {padding: 30},
  ph0: {paddingHorizontal: 0},
  ph5: {paddingHorizontal: 5},
  ph10: {paddingHorizontal: 10},
  ph15: {paddingHorizontal: 15},
  ph20: {paddingHorizontal: 20},
  ph25: {paddingHorizontal: 25},
  ph30: {paddingHorizontal: 30},
  pv0: {paddingVertical: 0},
  pv5: {paddingVertical: 5},
  pv10: {paddingVertical: 10},
  pv15: {paddingVertical: 15},
  pv20: {paddingVertical: 20},
  pv25: {paddingVertical: 25},
  pv30: {paddingVertical: 30},
  pb0: {paddingBottom: 0},
  pb10: {paddingBottom: 10},
  pb15: {paddingBottom: 15},
  pb20: {paddingBottom: 20},
  pb25: {paddingBottom: 25},
  pt0: {paddingTop: 0},
  pt5: {paddingTop: 5},
  pt10: {paddingTop: 10},
  pt15: {paddingTop: 15},
  pt20: {paddingTop: 20},
  pt25: {paddingTop: 25},
  pl0: {paddingLeft: 0},
  pl10: {paddingLeft: 10},
  pl5: {paddingLeft: 5},
  pl15: {paddingLeft: 15},
  pl20: {paddingLeft: 20},
  pl25: {paddingLeft: 25},
  pr0: {paddingRight: 0},
  pr10: {paddingRight: 10},
  pr5: {paddingRight: 5},
  pr15: {paddingRight: 15},
  pr20: {paddingRight: 20},
  pr25: {paddingRight: 25},
  // Spacing - Margin
  m0: {margin: 0},
  m5: {margin: 5},
  m10: {margin: 10},
  m15: {margin: 15},
  m20: {margin: 20},
  m25: {margin: 25},
  m30: {margin: 30},
  mb0: {marginBottom: 0},
  mb5: {marginBottom: 5},
  mb10: {marginBottom: 10},
  mb15: {marginBottom: 15},
  mb20: {marginBottom: 20},
  mb25: {marginBottom: 25},
  mb30: {marginBottom: 30},
  mt0: {marginTop: 0},
  mt5: {marginTop: 5},
  mt10: {marginTop: 10},
  mt15: {marginTop: 15},
  mt20: {marginTop: 20},
  mt25: {marginTop: 25},
  mt30: {marginTop: 30},
  ml0: {marginLeft: 0},
  ml5: {marginLeft: 5},
  ml10: {marginLeft: 10},
  ml15: {marginLeft: 15},
  ml20: {marginLeft: 20},
  ml25: {marginLeft: 25},
  ml30: {marginLeft: 30},
  mr0: {marginRight: 0},
  mr5: {marginRight: 5},
  mr10: {marginRight: 10},
  mr15: {marginRight: 15},
  mr20: {marginRight: 20},
  mr25: {marginRight: 25},
  mr30: {marginRight: 30},
  mv0: {marginVertical: 0},
  mv5: {marginVertical: 5},
  mv10: {marginVertical: 10},
  mv15: {marginVertical: 15},
  mv20: {marginVertical: 20},
  mv25: {marginVertical: 25},
  mv30: {marginVertical: 30},
  mh0: {marginHorizontal: 0},
  mh5: {marginHorizontal: 5},
  mh10: {marginHorizontal: 10},
  mh15: {marginHorizontal: 15},
  mh20: {marginHorizontal: 20},
  mh25: {marginHorizontal: 25},
  mh30: {marginHorizontal: 30},
  // Flex & Wrap
  flexWrapRow: {flexDirection: 'row', flexWrap: 'wrap'},
  flexRow: {flexDirection: 'row'},
  flexColumn: {flexDirection: 'column'},
  flexRowReverse: {flexDirection: 'row-reverse'},
  flexColumnReverse: {flexDirection: 'column-reverse'},
  flexWrap: {flexWrap: 'wrap'},
  flexCenter: {flex: 1, justifyContent: 'center', alignItems: 'center'},
  // Justify Content
  justifyContentCenter: {justifyContent: 'center'},
  justifyContentFlexEnd: {justifyContent: 'flex-end'},
  justifyContentFlexStart: {justifyContent: 'flex-start'},
  justifyContentSpaceBetween: {justifyContent: 'space-between'},
  // Align Self
  alignSelfFlexStart: {alignSelf: 'flex-start'},
  alignSelfFlexEnd: {alignSelf: 'flex-end'},
  alignSelfCenter: {alignSelf: 'center'},
  // Align Items
  alignItemsCenter: {alignItems: 'center'},
  alignItemsFlexStart: {alignItems: 'flex-start'},
  alignItemsFlexEnd: {alignItems: 'flex-end'},
  // Text Align
  textAlignLeft: {textAlign: 'left'},
  textAlignCenter: {textAlign: 'center'},
  textAlignRight: {textAlign: 'right'},
  // Text Colors
  textDanger: {color: 'red'},
  separator: {
    height: 0.5,
    width: '100%',
    alignSelf: 'flex-end',
  },
  hasBorder: {
    borderWidth: 1,
  },
  br15: {
    borderRadius: 15,
  },
  br10: {
    borderRadius: 10,
  },
  br5: {
    borderRadius: 5,
  },
  noBorder: {
    borderWidth: 0,
  },
  fontNormal: {
    //fontFamily: FontFamily.regular,
  },
  fontMedium: {
    //fontFamily: FontFamily.medium,
  },
  fontSemiBold: {
    //fontFamily: FontFamily.semiBold,
  },
  fontBold: {
    //fontFamily: FontFamily.bold,
  },
  relative: {
    position: 'relative',
  },
  absolute: {
    position: 'absolute',
  },
  textCapitalize: {
    textTransform: 'capitalize',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  cornerView: {
    flex: 1,
    backgroundColor: lightTheme.colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: 10,
  },
  shadowProp: {
    ...Platform.select({
      android: {
        elevation: 4,
      },
      ios: {
        shadowColor: 'rgba(0,0,0,0.2)',
        shadowOffset: {width: -2, height: 4},
        shadowOpacity: 0.7,
        shadowRadius: 8,
      },
    }),
  },

  // greyContainer: {
  //   flex: 1,
  //   backgroundColor: lightTheme.colors.lightGray,
  //   // background: lightTheme.colors.crystalSky,
  // },
  // noData: {
  //   textAlign: 'center',
  //   fontSize: 18,
  //   marginTop: 30,
  //   color: lightTheme.colors.blackText,
  // },
  // disabled: {
  //   color: lightTheme.colors.borderGreyTint,
  //   borderColor: lightTheme.colors.borderGreyTint,
  // },
  // disabledBackground: {
  //   backgroundColor: lightTheme.colors.borderGreyTint,
  //   borderColor: lightTheme.colors.borderGreyTint,
  // },
  disabledOPacity: {
    opacity: 0.5,
  },
  // gap10: {
  //   gap: 10,
  // },

  // disabledButtonStyle: {
  //   backgroundColor: lightTheme.colors.borderGreyTint,
  //   borderWidth: 0,
  // },
  mh24: {
    marginHorizontal: 24,
  },
  // textLabel: {
  //   color: lightTheme.colors.grey,
  //   fontFamily: FontFamily.medium,
  //   fontSize: 14,
  // },
  inverseCornerView: {
    flex: 1,
    backgroundColor: lightTheme.colors.white,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  body: {
    flex: 1,
    // backgroundColor: lightTheme.colors.lightGray,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingHorizontal: 24,
    paddingVertical: 30,
  },
  container: {
    width: '100%',
    backgroundColor: lightTheme.colors.white,
    paddingHorizontal: moderateScale(18),
    paddingVertical: moderateScale(20),
    borderRadius: 8,
  },
  // highlightText: {
  //   color: lightTheme.colors.highlight,
  // },
  // buttonGreen: {
  //   backgroundColor: lightTheme.colors.button,
  //   borderColor: lightTheme.colors.button,
  // },
  errorMsgBox: {
    alignItems: 'center',
    // backgroundColor: lightTheme.colors.errorBackground,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    // borderTopColor: lightTheme.colors.darkRed,
    borderTopWidth: 1.5,
    flexDirection: 'row',
    gap: 12,
    height: 45,
    paddingLeft: 10,
    paddingRight: 10,
    marginBottom: 5,
  },

  errorMsgText: {
    // color: lightTheme.colors.blackText,
    fontSize: 12,
    // fontFamily: FontFamily.regular,
    width: '80%',
  },
  dashBoardgraphTextArea: {width: 140, height: 140},
  extraView: {
    height: moderateScale(250),
  },
});
export default themeStyles;
